# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:android)

platform :android do
  desc "Build APK"
  lane :build_apk do
    sh "flutter build apk --release --obfuscate --split-debug-info=./build/app/outputs/flutter-apk/symbols"
  end

  desc "Build App Bundle"
  lane :build_bundle do
    sh "flutter build appbundle --release --obfuscate --split-debug-info=./build/app/outputs/bundle/release/symbols"
  end
end
