name: Builds
on: workflow_dispatch

# Declare default permissions
permissions:
  contents: write

jobs:
  build:
    name: Build and Release Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mobile code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
      - run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Code generation
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release

      - name: Locate APK
        run: ls -R build/app/outputs/flutter-apk/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: apk-release-${{ github.run_number }}
          draft: true
          prerelease: false
          generate_release_notes: true
          files: build/app/outputs/flutter-apk/app-release.apk
