name: Draft Github Release
on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      version:
        description: "Tag to create (e.g. v0.4.0). Must include 'v' and must match pubspec"
        required: true
        default: "v0.4.0"
        type: string

# Declare default permissions as write for releases.
permissions:
  contents: write

jobs:
  draft-release:
    name: Draft Github release
    runs-on: ubuntu-latest
    steps:
      - name: Draft release with release notes
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          draft: true
          prerelease: false
          generate_release_notes: true
